// <auto-generated />
using ApiCNH.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiCNH.Migrations
{
    [DbContext(typeof(MedicionesContext))]
    partial class MedicionesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiCNH.Models.Mediciones", b =>
                {
                    b.Property<long>("MedicionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Medicion")
                        .HasColumnType("float");

                    b.Property<string>("MedicionDescripcion")
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PiezaId")
                        .HasColumnType("int");

                    b.HasKey("MedicionId");

                    b.HasIndex("PiezaId");

                    b.ToTable("Mediciones");

                    b.HasData(
                        new
                        {
                            MedicionId = 1L,
                            Medicion = 140.5,
                            MedicionDescripcion = "Descripcion 1",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 2L,
                            Medicion = 140.30000000000001,
                            MedicionDescripcion = "Descripcion 2",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 3L,
                            Medicion = 140.09999999999999,
                            MedicionDescripcion = "Descripcion 3",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 4L,
                            Medicion = 140.30000000000001,
                            MedicionDescripcion = "Descripcion 4",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 5L,
                            Medicion = 139.59999999999999,
                            MedicionDescripcion = "Descripcion 5",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 6L,
                            Medicion = 140.19999999999999,
                            MedicionDescripcion = "Descripcion 6",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 7L,
                            Medicion = 140.09999999999999,
                            MedicionDescripcion = "Descripcion 7",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 8L,
                            Medicion = 139.80000000000001,
                            MedicionDescripcion = "Descripcion 8",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 9L,
                            Medicion = 139.90000000000001,
                            MedicionDescripcion = "Descripcion 9",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 10L,
                            Medicion = 140.09999999999999,
                            MedicionDescripcion = "Descripcion 10",
                            PiezaId = 1
                        },
                        new
                        {
                            MedicionId = 11L,
                            Medicion = 150.40000000000001,
                            MedicionDescripcion = "Descripcion 11",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 12L,
                            Medicion = 150.5,
                            MedicionDescripcion = "Descripcion 12",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 13L,
                            Medicion = 150.30000000000001,
                            MedicionDescripcion = "Descripcion 13",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 14L,
                            Medicion = 150.09999999999999,
                            MedicionDescripcion = "Descripcion 14",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 15L,
                            Medicion = 150.30000000000001,
                            MedicionDescripcion = "Descripcion 15",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 16L,
                            Medicion = 149.59999999999999,
                            MedicionDescripcion = "Descripcion 16",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 17L,
                            Medicion = 150.19999999999999,
                            MedicionDescripcion = "Descripcion 17",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 18L,
                            Medicion = 150.09999999999999,
                            MedicionDescripcion = "Descripcion 18",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 19L,
                            Medicion = 149.80000000000001,
                            MedicionDescripcion = "Descripcion 19",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 20L,
                            Medicion = 149.90000000000001,
                            MedicionDescripcion = "Descripcion 20",
                            PiezaId = 2
                        },
                        new
                        {
                            MedicionId = 21L,
                            Medicion = 160.09999999999999,
                            MedicionDescripcion = "Descripcion 21",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 22L,
                            Medicion = 160.40000000000001,
                            MedicionDescripcion = "Descripcion 22",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 23L,
                            Medicion = 160.5,
                            MedicionDescripcion = "Descripcion 23",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 24L,
                            Medicion = 160.30000000000001,
                            MedicionDescripcion = "Descripcion 24",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 25L,
                            Medicion = 160.09999999999999,
                            MedicionDescripcion = "Descripcion 25",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 26L,
                            Medicion = 160.30000000000001,
                            MedicionDescripcion = "Descripcion 26",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 27L,
                            Medicion = 159.59999999999999,
                            MedicionDescripcion = "Descripcion 27",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 28L,
                            Medicion = 160.19999999999999,
                            MedicionDescripcion = "Descripcion 28",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 29L,
                            Medicion = 160.09999999999999,
                            MedicionDescripcion = "Descripcion 29",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 30L,
                            Medicion = 159.80000000000001,
                            MedicionDescripcion = "Descripcion 30",
                            PiezaId = 3
                        },
                        new
                        {
                            MedicionId = 31L,
                            Medicion = 170.09999999999999,
                            MedicionDescripcion = "Descripcion 31",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 32L,
                            Medicion = 170.40000000000001,
                            MedicionDescripcion = "Descripcion 32",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 33L,
                            Medicion = 170.5,
                            MedicionDescripcion = "Descripcion 33",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 34L,
                            Medicion = 170.30000000000001,
                            MedicionDescripcion = "Descripcion 34",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 35L,
                            Medicion = 170.09999999999999,
                            MedicionDescripcion = "Descripcion 35",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 36L,
                            Medicion = 170.30000000000001,
                            MedicionDescripcion = "Descripcion 36",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 37L,
                            Medicion = 169.59999999999999,
                            MedicionDescripcion = "Descripcion 37",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 38L,
                            Medicion = 170.19999999999999,
                            MedicionDescripcion = "Descripcion 38",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 39L,
                            Medicion = 170.09999999999999,
                            MedicionDescripcion = "Descripcion 39",
                            PiezaId = 4
                        },
                        new
                        {
                            MedicionId = 40L,
                            Medicion = 169.80000000000001,
                            MedicionDescripcion = "Descripcion 40",
                            PiezaId = 4
                        });
                });

            modelBuilder.Entity("ApiCNH.Models.Pieza", b =>
                {
                    b.Property<int>("PiezaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PiezaDescripcion")
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("PiezaMedida")
                        .HasColumnType("float");

                    b.Property<string>("PiezaNombre")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PiezaId");

                    b.ToTable("Piezas");

                    b.HasData(
                        new
                        {
                            PiezaId = 1,
                            PiezaDescripcion = "Freno descripcion 140mm",
                            PiezaMedida = 140.0,
                            PiezaNombre = "Freno disco 140mm"
                        },
                        new
                        {
                            PiezaId = 2,
                            PiezaDescripcion = "Freno descripcion 150mm",
                            PiezaMedida = 150.0,
                            PiezaNombre = "Freno disco 150mm"
                        },
                        new
                        {
                            PiezaId = 3,
                            PiezaDescripcion = "Freno descripcion 160mm",
                            PiezaMedida = 160.0,
                            PiezaNombre = "Freno disco 160mm"
                        },
                        new
                        {
                            PiezaId = 4,
                            PiezaDescripcion = "Freno descripcion 170mm",
                            PiezaMedida = 170.0,
                            PiezaNombre = "Freno disco 170mm"
                        });
                });

            modelBuilder.Entity("ApiCNH.Models.Mediciones", b =>
                {
                    b.HasOne("ApiCNH.Models.Pieza", "Pieza")
                        .WithMany("Mediciones")
                        .HasForeignKey("PiezaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pieza");
                });

            modelBuilder.Entity("ApiCNH.Models.Pieza", b =>
                {
                    b.Navigation("Mediciones");
                });
#pragma warning restore 612, 618
        }
    }
}
